[project]
name = 'kill-admins'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.admin-killer]
path = 'contracts/admin-killer.clar'
clarity_version = 2
epoch = 2.5

[contracts.pepe]
path = 'contracts/pepe.clar'
clarity_version = 2
epoch = 2.5

[contracts.stackswap-dao-v5k]
path = 'contracts/stackswap-dao-v5k.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
